export const TOPICS_REQUEST = "LANDING_TOPICS_REQUEST";
export const TOPICS_REQUEST_ERROR = "LANDING_TOPICS_REQUEST_ERROR";
export const TOPICS_REQUEST_SUCCESS = "LANDING_TOPICS_REQUEST_SUCCESS";

export const CAROUSEL_REQUEST = "LANDING_CAROUSEL_REQUEST";
export const CAROUSEL_REQUEST_ERROR = "LANDING_CAROUSEL_REQUEST_ERROR";
export const CAROUSEL_REQUEST_SUCCESS = "LANDING_CAROUSEL_REQUEST_SUCCESS";
